name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # デプロイディレクトリの準備
          sudo mkdir -p /var/www/pdfcutter-app
          sudo chown -R ubuntu:ubuntu /var/www/pdfcutter-app
          cd /var/www/pdfcutter-app
          
          # 初回の場合はクローン、そうでなければプル
          if [ ! -d ".git" ]; then
            git clone https://github.com/bibirimannya/pdfcutter-app.git .
          else
            git pull origin main
          fi
          
          # Dockerコンテナの更新
          docker-compose down || true
          docker-compose build --no-cache
          docker-compose up -d
          docker system prune -f || true
